#!/usr/bin/env python3
# encoding: utf-8
"""
FeedManager.py
This class handles converting the tweets into a RSS feed file.
"""

from ManagerBase import *
from typing import List
from RSSItemTuple import *
from GlobalSettings import *
import feedgenerator


class FeedManager(ManagerBase):
    """
    This class takes in a list of tweets and builds the input RSS file

    """

    # *********************************************************************************************
    def __init__(self):
        """Initialize ourselves

        """

        super().__init__()

    # *********************************************************************************************
    def WriteFeed(self, inItems: List[RSSItemTuple]) -> bool:
        """
        Takes the list of input items and writes it to a RSS feed

        :param inItems: list of RSSItemTuples
        :return: True on success, False otherwise
        """

        try:
            # Create the overall feed metadata
            myFeedGenerator = feedgenerator.Rss201rev2Feed(
                    title="Brian's Twitter",
                    link="http://www.digitalmaddox.com/myttrss/twitterfeed.rss",
                    description="Generated by pyTwittertoRSS",
                    language="en",
                    author_name="Brian G. Maddox",
                    author_email="brian.maddox@gmail.com")

            # Go through each item and add it to the feed
            for feedItem in inItems:
                tAuthor = "{username}".format(username=feedItem.user_name)

                tTitle = "{author}: {tweettext}".format(author=tAuthor,
                                                        tweettext=feedItem.tweet_text)
                tDescription = "<b>Author:</b> {tauthor}<br><b>Tweet:</b> {fulltweet}<br><b>URLS:</b> {urls}". \
                    format(tauthor=tAuthor,
                           fulltweet=feedItem.tweet_text,
                           urls=feedItem.found_urls)

                myFeedGenerator.add_item(title=tTitle,
                                         link=feedItem.tweet_url,
                                         author_name=tAuthor,
                                         author_link=feedItem.user_url,
                                         pubdate=feedItem.created_at,
                                         description=tDescription)

            # Now write it to a file
            with open(feedFilename, 'w') as feedFile:
                myFeedGenerator.write(feedFile, 'utf-8')

        except Exception as tExcept:
            self.logger.critical("*** Unable to create the feed!")
            self.logger.error(tExcept)
            return False

        return True
